Feat/erc721 testing (#353) (#418)
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Minimal integration testing for the solmates erc721 contract

Resolves #353 

## What is the new behavior?

Richer tests based on those found
[here](https://github.com/transmissions11/solmate/blob/main/src/test/ERC721.t.sol)

- All tests involving burning or transferring will fail, because they
involve unchecked arithmetic ops.
- I reproduced a MWE here #415 and in the telegram danilo suggested a
fix, which I added to the example and resolved it
- With those changes in #415, tests should pass 100% (or atleast they do
locally)
- I made two changes to the solmates logic to adapt to our test runner,
will comment in line but briefly
- safeMint / safeTransfer were methods that had dispatching based on
arguments. I renamed the variants off each method that take a data
argument safeMint2 and safeTransfer2.
- Justification: when I tried to call the methods as is, I was seeing
the following error:
  ```python
    def get_function_by_identifier(
        fns: Sequence[ContractFunction], identifier: str
    ) -> ContractFunction:
        if len(fns) > 1:
           raise ValueError(
                'Found multiple functions with matching {0}. '
                'Found: {1!r}'.format(identifier, fns)
ValueError: Found multiple functions with matching name. Found:
[<Function safeMint(address,uint256,bytes)>, <Function
safeMint(address,uint256)>
   ```
- In the `ERC721Recipient` contract, there is a public address field
named 'from.' I renamed this to from_.
- Justification: when trying to call the getter 'from' in python I was
getting this error, which I presumed to mean there was some overlap in
the kakarot wrapping:
    ```shell
File
"./starknet/kakarot/tests/integration/solidity_contracts/Solmate/test_erc721.py",
line 399
       recipient_from = await erc_721_recipient.from()
SyntaxError: invalid syntax
    ```


## Other information

<!-- Give an estimate of the time you spent on this PR in terms of work
days. Did you spend 0.5 days on this PR or rather 2 days? -->
Time spent on this PR:  1 day

<!-- Any other information that is important to this PR such as
screenshots of how the component looks before and after the change. -->

Co-authored-by: kakarot CI <sayajin-labs@users.noreply.github.com>